### ISSUE TITLE
Implementation of Player 2 in exp_replay.py

### ISSUE THREAD

**Issue by way151** [krm9c/Balanced-Continual-Learning#1]
Hello! This is a very good paper. I understand the technical meaning of the proposed loss, but I have a small question in `class NASH` in `exp_replay.py`: `J_P` and `J_PN_theta` are the same loss. I wonder if we just optimize `J_th` without `-J_PN_theta` and  `+J_P` as they are erased by each other. Thanks a lot.

**Comment by krm9c** [comment]
What you are saying is correct and could be done under the condition that beta is set to one, which is what I do in my code. When beta  is not one, you will get beta*J_P + J_th + J_x, that is, why you have those two terms in there and they do not cancel out. 

If beta is equal to one and you want to cancel the two terms out, please be mindful of the cost magnitudes, for instance, if the J_P magnitude is too large and J_PN_theta  is not there to cut the magnitude, you will observe large forgetting.

**Comment by way151** [comment]
I get it, thank you!

**Comment by krm9c** [comment]
Thank you for reaching out and reading the paper. Please feel free to comment for any issues you may face.
